FROM oven/bun:debian

WORKDIR /shared

COPY --from=shared . .

WORKDIR /app

COPY package.json .
RUN bun install

COPY src ./src
COPY tsconfig.json .
COPY .env .

RUN bunx prisma generate

CMD ["bun", "dev"]